# Generated by Django 5.2.8 on 2025-11-30 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifiti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ['-date_registered'], 'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], help_text='Relationship to patient', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Medical conditions (e.g., Diabetes, Hypertension, Asthma)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any allergies (e.g., Penicillin, Peanuts, Shellfish)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Your blood type', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Your date of birth (YYYY-MM-DD)', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Full name of emergency contact', max_length=150),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], help_text='Select your gender', max_length=1),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='insurance_number',
            field=models.CharField(blank=True, help_text='Insurance policy number', max_length=150),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, help_text='Insurance company name', max_length=150),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications (e.g., Aspirin 500mg daily, Metformin 1000mg)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number (e.g., +1234567890)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='URL to your profile photo'),
        ),
    ]
