# Generated by Django 5.2.8 on 2025-11-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifiti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='time',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
