# Generated by Django 5.2.8 on 2025-12-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifiti', '0003_doctor_created_at_doctor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='medifiti.service'),
        ),
    ]
