# Generated by Django 5.2.8 on 2025-12-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifiti', '0004_doctor_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='facility_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facility',
            },
        ),
    ]
